notifications 2.0

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -1,47 +1,48 @@
-name: Run tests
+name: Java CI
 
 on:
   push:
-    branches-ignore: 
+    branches-ignore:
       - 'main'
   pull_request:
-    branches: 
+    branches:
       - 'main'
 
 jobs:
+
   build:
     runs-on: ubuntu-latest
     
     steps:
-      - uses: actions/checkout@v3
+    - uses: actions/checkout@v3
+    - name: Set up JDK 17
+      uses: actions/setup-java@v3
+      with:
+        java-version: '17'
+        distribution: 'adopt'
+    - name: Build with Maven
+      working-directory: backend
+      run: mvn clean install
+    - name: Run tests
+      id: tests
+      working-directory: backend
+      run: mvn test
       
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'adopt'
-          
-      - name: Build with Maven
-        working-directory: backend
-        run: mvn clean install
+    - name: Check test results
+      if: ${{ steps.tests.outcome == 'failure' }}
+      run: exit 1
       
-      - name: Run tests
-        id: test
-        working-directory: backend
-        continue-on-error: true 
-        run: mvn test
-
-      - name: Check test results
-        run: |
-          if [[ "${{ steps.test.outcome }}" == "success" ]]; then
-            echo "Successs :)"
-          else
-            echo "Failure :("
-          fi
+    - name: Upload test results
+      if: ${{ always() }}
+      uses: actions/upload-artifact@v3
+      with:
+        name: test-results
+        path: backend/target/surefire-reports
+        
+    - name: Notify Success
+      if: ${{ steps.tests.outcome == 'success' }}
+      run: echo "✅ Tests passed!"
       
-      - name: Upload test results
-        if: ${{ always() }} 
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: backend/target/surefire-reports
+    - name: Notify Failure  
+      if: ${{ steps.tests.outcome == 'failure' }}
+      run: echo "❌ Tests failed!"
